export const DEFAULT_TIME_TO_SEARCH = 1000;
export const MIN_SIZE_TO_SEARCH = 3;
export const DEFAULT_MAX_FILE_SIZE_IN_BYTES = 2048 * 1000;
export const DEFAULT_QUANTITY_OF_LABELS_ON_PRINT = 30;
export const CEP_LENGTH = 8;